### ISSUE TITLE
Confused, why can't I push directly?

### ISSUE THREAD

**Issue by zle000** [GaijinEntertainment/daScript#1460]
```

def acall(a:lambda<():void>) {
    invoke(a);
}

[export]
def main() {

    unsafe {
        var arr = array<float2>() ;
        acall(@(){
            // let v = float2(0,1);
            // arr.push(v);
            arr.push(float2(0,2));
        });
    }

}
```

I need to create a constant, but I feel like the effect will be the same.（：

**Comment by borisbat** [comment]
can't reproduce. compiles fine with current master.

on a side note - ; at the end of lines are no longer necessary.

**Comment by zle000** [comment]
> can't reproduce. compiles fine with current master.
> 
> on a side note - ; at the end of lines are no longer necessary.

Than you for your replay~ ，I using the current master branch still has issues,
```
error[30304]: no matching functions or generics: __::builtin`push(array<float2>&, float2 const)
.\test.das:48:15
            arr.push(float2(0,2));
               ^
__::builtin`push(array<float2>&, float2 const)
while compiling: _lambda_thismodule_44_1`function(__this: _lambda_thismodule_44_1 explicit): void

candidate function:
        builtin`push(Arr: array<float2 aka numT> explicit; value: float2 ==const): void at builtin.das:135:4
                name is similar, typo?
                invalid argument 'value' (1). expecting 'float2 ==const', passing 'float2 const'
```
but~~
```

def acall(a:lambda<():void>) {
    invoke(a);
}

[export]
def main() {

    unsafe {
        var arr = array<float2>() ;
        acall(@(){
            let v = float2(0,1);  // it is ok, if not comment~~
            arr.push(v);            // it is ok, if not comment~~
            arr.push(float2(0,2));
        });
    }

}
```
If I removed the comments from those two lines of code, and it compiled successfully

I still have a other doubt：
```


def acall(a:lambda<():void>) {
    print(" calling \n");
    invoke(a);
    
}

[export]
def main() {
    var arr = array<float2>() ;
    
    unsafe {
        acall( @(){
            print(" pushing \n");
            let v = float2(0,1);
            arr.push(v);
            arr.push(float2(0,2));
            debug(arr); //has values
        });
    }
    print(" after pushing \n");

    debug(arr);         //  I think it should have the values, but it doesn't. ):

    var arr2 = array<float2>() ;
    arr2.push(float2(1,2));
    debug(arr2);
}
```

**Comment by borisbat** [comment]
on you 2nd note - arr is captured by move, not by reference. if capture is explicitly specified, i.e. 
```
        acall( @ capture(&arr) (){
            print(" pushing \n");
            let v = float2(0,1);
            arr.push(v);
            arr.push(float2(0,2));
            debug(arr); //has values
        });
```
arr will have values outside out lambda call.

**Comment by borisbat** [comment]
I've pushed hello_world.das with your example - and it compiles fine with the latest das on windows.

on that capture note, in the scenario above u'll do better with the block (vs the lambda).

**Comment by zle000** [comment]
> I've pushed hello_world.das with your example - and it compiles fine with the latest das on windows.
> 
> on that capture note, in the scenario above u'll do better with the block (vs the lambda).
> 
> additionally check out hello_new_syntax.das - options gen2 fits nicely to the style of formatting which you chose.

_Thank you for your help~  The capture work is fine._

_Well I still get the error push value -_- ~_

![2025-01-15 160425](https://github.com/user-attachments/assets/d43f7f09-59c0-4c99-9dae-f93df5316991)

**Comment by borisbat** [comment]
we've tried locally from a clean pull of the repository - and the issue is not reproducibel.
at this point its one of the two things.
1. your local build \ merge issues. could you please try the clean build and\or clean git pull (like delete everything, start over?)
2. compiler version. if clean build does not help - we'll need build logs

**Comment by zle000** [comment]
> we've tried locally from a clean pull of the repository - and the issue is not reproducibel. at this point its one of the two things.
> 
> 1. your local build \ merge issues. could you please try the clean build and\or clean git pull (like delete everything, start over?)
> 2. compiler version. if clean build does not help - we'll need build logs

I  clone the master into a new fold then gen vs2022 project,then open vs to build, here is the log 
os: Microsoft Windows [10.0.19045.5371] 
os language is Chinese
[generate_msvc_2022.log](https://github.com/user-attachments/files/18449043/generate_msvc_2022.log)

[build.log](https://github.com/user-attachments/files/18449044/build.log)

and here is the test das code
```
options gen2

def callLam(lam:lambda<void>) {
    invoke(lam)        
}

[export]
def main() {

    callLam() @ {
        var arr = array<float2>()
        arr.push(float2(1,2))
    }

}

```
(:

**Comment by borisbat** [comment]
I got the issue reproduced, thank you. Looking.

**Comment by borisbat** [comment]
And fixed in https://github.com/GaijinEntertainment/daScript/pull/1469
The bug was due to const folding interfering with generic type infer and ordering of operations
